### ISSUE TITLE
Support of several warehouses on stock update

### ISSUE THREAD

**Issue by resslinger** [kinimodmeyer/tradebyte-sdk-php#13]
Hello,

we want to upload stocks to several warehouse.

According to the documentation (https://www.tradebyte.io/wp-content/uploads/2020/07/3018_stock-data-via-rest-api_en.pdf) this is possible.

Can you add support for this please?

**Comment by dominikmebs** [comment]
done, see release https://github.com/kinimodmeyer/tradebyte-sdk-php/releases/tag/v0.4.0
